### ISSUE TITLE
warnings/errors from other packages

### ISSUE THREAD

**Issue by tjmahr** [stan-dev/shinystan#130] opened 2016-08-29 16:12 UTC
Just a heads-up. It looks some API changes from other packages are interfering with shinystan. 

I'm running `launch_shinystan_demo()` in a clean R session.

On start-up, I get the following warning.

```
Warning: As of August 2016, 'colourInput()' has been deprecated and has moved to the 'colourpicker' package. Please use the 'colourpicker' package in the future.
```

On the posterior summary statistics page, I get the following error.

```
Warning: Error in : 'copySWF' is not an exported object from 'namespace:DT'
Stack trace (innermost first):
    94: getExportedValue
    93: ::
    92: stopifnot
    91: modifyList
    90: DT::datatable
    89: eval
    88: eval
    87: %>%
    86: reactive summary_stats [server_files/pages/estimate/server/summary_stats.R#4]
    75: summary_stats
    74: exprFunc [server_files/pages/estimate/server/summary_stats.R#42]
    73: widgetFunc
    72: func
    71: renderFunc
    70: output$all_summary_out
     3: shiny::runApp
     2: launch
     1: launch_shinystan_demo
```

It looks like this function was [removed recently](https://github.com/rstudio/DT/blob/master/NEWS.md#major-changes-1).

<details>
```
R version 3.3.1 (2016-06-21)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] shinystan_2.2.0 shiny_0.13.2   

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.6        plyr_1.8.4         base64enc_0.1-3    shinyjs_0.7       
 [5] tools_3.3.1        xts_0.9-7          digest_0.6.10      jsonlite_1.0      
 [9] gtable_0.2.0       lattice_0.20-33    Matrix_1.2-7       yaml_2.1.13       
[13] gridExtra_2.2.1    stringr_1.1.0      dygraphs_1.1.1-1   htmlwidgets_0.7   
[17] gtools_3.5.0       stats4_3.3.1       grid_3.3.1         DT_0.2            
[21] inline_0.3.14      R6_2.1.3           rstan_2.11.1       ggplot2_2.1.0     
[25] reshape2_1.4.1     magrittr_1.5       StanHeaders_2.11.0 threejs_0.2.2     
[29] scales_0.4.0       htmltools_0.3.5    shinythemes_1.0.1  rsconnect_0.4.3   
[33] mime_0.5           xtable_1.8-2       colorspace_1.2-6   httpuv_1.3.3      
[37] labeling_0.3       stringi_1.1.1      miniUI_0.1.1       munsell_0.4.3     
[41] markdown_0.7.7     zoo_1.7-13
```
</details>

**Comment by jgabry** [comment] 2016-08-29 16:19
Thanks for the heads up! I'll look into this today.

**Comment by bob-carpenter** [comment] 2016-08-29 17:51
Is this the kind of thing we can prevent by adding tests to
ShinyStan?

- Bob

> On Aug 29, 2016, at 6:12 PM, TJ Mahr <notifications@github.com> wrote:
> 
> Just a heads-up. It looks some API changes from other packages are interfering with shinystan.

...

**Comment by jgabry** [comment] 2016-08-29 18:22
There are lots of tests for shinystan. The problem is that there are two
different testing frameworks that are needed and currently one of them is
much easier than the other:

(1) Testing for the source code of the user-facing and internal functions
in the package (i.e. not the GUI but functions like launch_shinystan,
as.shinystan). The current tests have 97% line coverage for these
functions. While line coverage isn't everything when it comes to testing,
the tests are pretty good.

(2) Testing for the GUI. This is considerably harder to do when using Shiny
than when testing regular old R code like in (1). In order to best test the
source code for the GUI I would need to modify the way the that code is
written written so that the functions used by the GUI can also be called
from R without being part of the GUI. For a lot of the functions I already
do this, but for other functions it can be really difficult (although maybe
not impossible) because they rely on information only available when the
app is launched.

The functions relevant to this issue pertain to (2) (e.g. the
deprecated colourInput()
function is used interactively to select colors for some of the plots). But
I think there's a workaround here that would avoid some of the problems
posed by (2). For example, I could put all functions from other packages
that are used in the GUI into tests that just run those functions on their
own. This wouldn't be super useful in general, but it probably would have
caught the deprecations earlier.

**Comment by jgabry** [comment] 2016-08-29 18:36
Actually perhaps most relevant to this particular problem is that I do have
additional tests that I run locally before releasing (in addition to the
tests on github that are run by Travis) that do catch these
deprecations but because they involve launching the app I can't have Travis
or CRAN run them. I hadn't run them locally since the last release and so
didn't notice the problem.

**Comment by jgabry** [comment] 2016-08-29 20:18
@tjmahr I'm pretty sure these issues are now fixed on the develop branch.

**Comment by jgabry** [comment] 2016-08-29 20:19
I still need to sort a few details out but there shouldn't be anymore warnings/errors

**Comment by bob-carpenter** [comment] 2016-08-29 20:52
On Aug 29, 2016, at 8:22 PM, Jonah Gabry <notifications@github.com> wrote:
> 
> ...
> The functions relevant to this issue pertain to (2) (e.g. the
> deprecated colourInput()
> function is used interactively to select colors for some of the plots). But
> I think there's a workaround here that would avoid some of the problems
> posed by (2). For example, I could put all functions from other packages
> that are used in the GUI into tests that just run those functions on their
> own. This wouldn't be super useful in general, but it probably would have
> caught the deprecations earlier.

That sounds reasonable.  Would that mean if the package from
which the tests are drawn tries to change their API, they'd
have to get you to update ShinyStan first?

- Bob

P.S.  @T J Mohr:  Deprecating a function doesn't remove it, just warns that it's
no longer recommended and might go away in the future.  And ideally it prints
a message about how to upgrade.  It sounds like the functions in question
here were removed, not deprecated.  See:

   https://en.wikipedia.org/wiki/Deprecation#Software_deprecation

**Comment by jgabry** [comment] 2016-08-29 20:59
On Monday, August 29, 2016, Bob Carpenter <notifications@github.com> wrote:

>
> That sounds reasonable. Would that mean if the package from
> which the tests are drawn tries to change their API, they'd
> have to get you to update ShinyStan first?


If they follow the CRAN policies then they'd have to at least give a
reasonable amount of time to update ShinyStan (I forget exactly how much
time but it seemed reasonable when I read it).


> P.S. @T J Mohr: Deprecating a function doesn't remove it, just warns that
> it's
> no longer recommended and might go away in the future. And ideally it
> prints
> a message about how to upgrade. It sounds like the functions in question
> here were removed, not deprecated.
>

In this case we have both sort of: one function is deprecated (and has a
good message about how to upgrade) and for a different function (different
author too) one of the arguments is longer supported at all.

**Comment by tjmahr** [comment] 2016-08-29 21:01
Two weeks is a recommended amount of time. http://r-pkgs.had.co.nz/release.html#release-deps

**Comment by jgabry** [comment] 2016-08-30 15:55
TJ if it's not too much trouble can you confirm that the version currently
on the develop branch works for you? The posterior summary statistics page
shouldn't error anymore but the new way to do what was deprecated makes it
a bit cluttered and ugly at the top. I'll try to clean that up but I might
just submit the patched version to CRAN and clean it up next time if I
can't do it today.

Thanks again for reporting this.

Jonah

**Comment by tjmahr** [comment] 2016-08-30 17:50
```r
devtools::install_github("stan-dev/shinystan", ref = "develop")
#> Skipping install of 'shinystan' from a github remote, the SHA1 (9af50da4) has not changed since last install.
#>   Use `force = TRUE` to force installation

shinystan::launch_shinystan_demo()
#> Error in get(demo_name): object 'eight_schools' not found

library("shinystan")
#> Loading required package: shiny
#> 
#> This is shinystan version 2.2.1
launch_shinystan_demo()
#> 
#> Listening on http://127.0.0.1:5546
```
The posterior summary table shows up and I don't get any warnings about deprecations. The demo only works when I have the package loaded with `library`.

**Comment by jgabry** [comment] 2016-08-30 23:11
Ok thanks a lot for checking. I'll also take see if I can get the demo
working without having to call library first.

**Comment by jgabry** [comment] 2016-08-31 16:29
Ok `shinystan::launch_shinystan_demo()` should now work (using develop branch)

**Comment by jgabry** [comment] 2016-08-31 16:43
Closing this and submitting patched version for release

**Closed by jgabry** 2016-08-31 16:43 UTC
