### ISSUE TITLE
Can't use Shinystan to look at rstanarm glmer results

### ISSUE THREAD

**Issue by rayleigh** [stan-dev/shinystan#128] opened 2016-07-19 19:32 UTC
For a project, I used RStanarm's glmer function in the following way:

stan_fit <- stan_glmer(formula = formula(reg_formula), data = data_matrix, 
                         family = "binomial", iter = 500, sample_file = output_filename)

However, when I tried to upload the files and look at the results in Shinystan, I got the following warnings and error messages:

**> naes_one <- read_stan_csv(c("Annenberg_analysis_1_sample_output1", "Annenberg_analysis_1_sample_output2", "Annenberg_analysis_1_sample_output3", "Annenberg_analysis_1_sample_output4"))**
There were 12 warnings (use warnings() to see them)
**> warnings()**
Warning messages:
1: In if (adapt_term_lineno == len) adaptation_info <- "" else { ... :
  the condition has length > 1 and only the first element will be used
2: In (adapt_term_lineno + 1):(time_lineno - 1) :
  numerical expression has 2 elements: only the first used
3: In 1:(adapt_term_lineno - 1) :
  numerical expression has 2 elements: only the first used
4: In if (adapt_term_lineno == len) adaptation_info <- "" else { ... :
  the condition has length > 1 and only the first element will be used
5: In (adapt_term_lineno + 1):(time_lineno - 1) :
  numerical expression has 2 elements: only the first used
6: In 1:(adapt_term_lineno - 1) :
  numerical expression has 2 elements: only the first used
7: In if (adapt_term_lineno == len) adaptation_info <- "" else { ... :
  the condition has length > 1 and only the first element will be used
8: In (adapt_term_lineno + 1):(time_lineno - 1) :
  numerical expression has 2 elements: only the first used
9: In 1:(adapt_term_lineno - 1) :
  numerical expression has 2 elements: only the first used
10: In if (adapt_term_lineno == len) adaptation_info <- "" else { ... :
  the condition has length > 1 and only the first element will be used
11: In (adapt_term_lineno + 1):(time_lineno - 1) :
  numerical expression has 2 elements: only the first used
12: In 1:(adapt_term_lineno - 1) :
  numerical expression has 2 elements: only the first used
**> launch_shinystan(naes_one)**

Creating shinystan object...
Error in if (.used_vb(x) || !(algo %in% c("NUTS", "HMC"))) warning("Many features are only available for models fit using\n            algorithm NUTS or algorithm HMC.",  : 
  missing value where TRUE/FALSE needed

**Comment by rayleigh** [comment] 2016-07-19 20:03
I just tried looking at the Stanfit object in Shinystan right after getting glmer results. Shinystan launches fine in that case. So, is this an Rstanarm issue instead?

**Comment by jgabry** [comment] 2016-07-20 01:19
Thanks Rayleigh. I'm not sure yet what the problem is, but it might
be either an issue with shinystan + stanfit objects created from csv files
(this at least used to work pre-2.10).

Can you send me the csv files? Or trimmed csv files (if they're big). I
think I should be able to figure it out pretty quickly if I can reproduce
it exactly.

**Comment by rayleigh** [comment] 2016-07-20 03:06
One csv file is around 20 MB. What can I trim to make it smaller for you?

**Comment by jgabry** [comment] 2016-07-20 04:52
I probably only need a small subset of the posterior draws. So you could
discard everything after the first 50 iterations or something like that.

**Comment by mkiang** [comment] 2017-06-23 17:04
Was this ever resolved? I get the same error when trying to read in a sample file generated by `RStan`.

**Comment by martinmodrak** [comment] 2018-03-10 09:41
The problem persists as of Stan 2.17.0, the problem is when reading fits from CSV files. A minimal reproducible example:

```
stan_code <- "parameters { real a; } model { a ~ normal(0,1); }"
fit <- stan(model_code = stan_code, sample_file = "samples.csv", chain = 1, iter = 100)
fit2 <- read_stan_csv("samples.csv")

#launch_shinystan(fit) #Works OK
launch_shinystan(fit2)
```

Results in 
```
Error in if (.used_vb(x) || !(algo %in% c("NUTS", "HMC"))) warning("Many features are only available for models fit using\n            algorithm NUTS or algorithm HMC.",  : 
  missing value where TRUE/FALSE needed
```

**Comment by martinmodrak** [comment] 2018-03-10 10:24
So I filed a pull request with a fix. In the long run it might be more reasonable to unify the CSV output of ```rstan::sampling``` and CmdStan to avoid those hacks.

**Comment by jgabry** [comment] 2018-04-29 22:01
PR already merged and release is coming so I'm closing this one. Thanks @martinmodrak! I agree that in the long term unifying the output is desirable.

**Closed by jgabry** 2018-04-29 22:01 UTC
